### ISSUE TITLE
No overrides listed in the panel

### ISSUE THREAD

**Issue by ranveer5289** [redvanworkshop/sfcc-cartridge-overrides-vscode-extension#1]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the Bug

Hello,

Thank you for this nice extension. In my workspace(multi root), I do not get any overrides listed in the panel. I simply get a blank panel.
<img width="476" alt="Screenshot 2022-04-02 at 19 16 23" src="https://user-images.githubusercontent.com/826004/161393912-e70d86b3-5fd8-445c-9936-48027b45de99.png">

I already checked the extension configuration and I have configured the correct cartridge path. The `SFCC Cartridge Overrides` log channel lists my cartridge correctly and does not show any error.

What am I missing here?

### Steps To Reproduce

1. Create a new multi-root workspace and add applicable cartridges to it.
2. Open the CartridgeOverrides panel
3. Observe that no cartridges are listed.

### Environment

```markdown
- OS:MacOS Catalina
- Node:11.15.0
- npm:6.7.0
```

**Comment by manifestinteractive** [comment]
@ranveer5289 hmmm, this seems to be happening to a few people.  Can you try one thing for me to see if it resolves your issue?  If you move you mouse over the CARTRIDGE PATH panel, you should see a Refresh icon.  With others that had this issue, it seems like it just got stuck loading, and clicking the refresh icon triggers a reload, and then the correct data appeared.

Even if this fixes your issue, let's keep this bug open, as it should not require that you click refresh.  Something else is going on here.  I am pretty sure it has to do with Multi-root Workspaces, but either way, I will get it sorted ASAP.

**Comment by ranveer5289** [comment]
@manifestinteractive : I tried that but unfortunately no luck. I still do not see any data.
Are there any additional debug logs that I can check to help you further in debugging?

**Comment by manifestinteractive** [comment]
@ranveer5289 there is, but I doubt there will be anything in there.  We can try though :)

If you have the `Output` tab open ( usually visible when you have the terminal window open ), there are two custom loggers you can try.  The first is the one made for this extension.  If you have my extension active ( panels are visible ) you can open your Output tab, then you should see a drop down list in the top right ( probably has `Tasks` selected, since that's the default ).  If you look for `SFCC Cartridge Overrides` in that list, you should see some output, including which cartridges it found, and what it thinks your workspace path is.  Anything from there you can share would be fantastic.

The other Output option you can try would be the error log for extensions, which you can find in `Log (Extension Host)` and  if my extension is throwing errors, you should see some nasty errors in there from `RedVanWorkshop.sfcc-cartridge-overrides`.  If there are any errors that you can share, those would also be helpful... though there is no easy way to search that one.  You could right click and `clear` the output, and try reloading / refreshing my cartridge like you did before, and that should re-trigger the errors if you were getting any.

**Comment by manifestinteractive** [comment]
@ranveer5289 my gut is telling me that when you check the `SFCC Cartridge Overrides` output, you are not going to have anything next to `WORKSPACE:` as that would explain why you are not seeing anything ... because it either could not find your workspace, or is using the wrong one.  If it found the wrong one, then it would not have found anything related to SFCC and probably just returned an error that should have thrown an exception in that Extension Host logger.

**Comment by ranveer5289** [comment]
@manifestinteractive : 

This is the output I see so I do not see any `WORKSPACE` entry in the log and only see `CARTRIDGE PATH`

```
CARTRIDGE PATH:
- app_some_cartridge_1
- app_some_cartridge_2
- app_some_cartridge_3
- app_some_cartridge_4
- bc_util
- bc_fileimpex
- bc_job_components
- plugin_checkout
- plugin_dynamicforms
- plugin_dis
- plugin_gdpr_selfservice
- plugin_datadownload
- app_some_cartridge_5
- plugin_sitemap
- int_adyen
- app_some_cartridge_6
- app_some_cartridge_7
- app_storefront_base
```

From the Extension Host logger, I see below errors:

```
[2022-04-04 10:32:18.470] [exthost] [error] Error: 
	at g.cmp (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:59:61964)
	at _.findSubstr (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:59:65972)
	at c.getWorkspaceFolder (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:89:33653)
	at w.getWorkspaceFolder (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:89:36509)
	at Object.getWorkspaceFolder (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:99:43817)
	at Object.getWorkspace (/Users/ranveer/.vscode/extensions/redvanworkshop.sfcc-cartridge-overrides-1.0.0/extension/util.js:95:31)
	at new Cartridges (/Users/ranveer/.vscode/extensions/redvanworkshop.sfcc-cartridge-overrides-1.0.0/extension/Cartridges.js:31:31)
	at activate (/Users/ranveer/.vscode/extensions/redvanworkshop.sfcc-cartridge-overrides-1.0.0/extension/index.js:48:22)
	at Function._callActivateOptional (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:90:16070)
	at Function._callActivate (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:90:15731)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:90:13549
	at processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async g._activate (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:85:8154)
	at async g._waitForDepsThenActivate (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:85:8096)
	at async g._initialize (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:85:7460)
```

**Comment by manifestinteractive** [comment]
Perfect, this helps a lot.  It's exactly what I thought, it could not find your workspace.  I'll work on recreating your setup locally and retest it.  Multiroot is a pain in the butt sometimes, but it should work after I get a fix out for it.

**Comment by ranveer5289** [comment]
@manifestinteractive : great! thanks a lot

Just for reference, below is how my `.code-workspace` file looks

```
{
	"folders": [
		{
			"path": "../projects/client_name/storefront/cartridges"
		},
		{
			"path": "../projects/agency_name-sfra-base/agency_name-base/cartridges/plugin_checkout"
		},
		{
			"path": "../projects/agency_name-sfra-base/agency_name-base/cartridges/plugin_dynamicforms"
		},
		{
			"path": "../projects/agency_name-sfra-base/plugin_dis"
		},
		{
			"path": "../projects/agency_name-sfra-base/agency_name-base/cartridges/app_agency_name_base"
		},
		{
			"path": "../projects/agency_name-sfra-base/plugin_sitemap"
		},
		{
			"path": "../projects/agency_name-sfra-base/agency_name_fixes/cartridges/app_storefront_fix"
		},
		{
			"path": "../projects/agency_name-sfra-base/storefront-reference-architecture/cartridges"
		},
		{
			"path": "../projects/agency_name-sfra-base/agency_name_fixes/cartridges/modules"
		},
		{
			"path": "../projects/agency_name-sfra-base/plugin_gdpr_selfservice"
		},
		{
			"path": "../projects/agency_name-sfra-base/plugin_wishlists/cartridges"
		},
		{
			"path": "../projects/agency_name-sfra-base/agency_name_fixes/cartridges/plugin_wishlist_fix"
		},
		{
			"path": "../projects/agency_name-sfra-base/agency_name_fixes/cartridges/lib_productlist_fix"
		},
		{
			"path": "../projects/agency_name-sfra-base/plugin_productcompare"
		},
		{
			"path": "../projects/agency_name-sfra-base/lib_productlist"
		},
		{
			"path": "../projects/agency_name-sfra-base/plugin_datadownload"
		},
		{
			"path": "../projects/agency_name-sfra-base/agency_name_integration/cartridges/adyen/cartridges"
		},
		{
			"path": "../projects/job-components/cartridges"
		},
		{
			"path": "../projects/link_agency_name_oms/cartridges"
		},
		{
			"path": "../projects/agency_name-sfra-base/agency_name-base/cartridges/bc_util"
		},
		{
			"path": "../../../clone/rvw_developers_core/cartridges"
		}
	],
	"settings": {}
}
```

**Comment by mittinti** [comment]
Same issue to me as well.

**Comment by manifestinteractive** [comment]
This should be resolved now in https://marketplace.visualstudio.com/items?itemName=PeterSchmalfeldt.sfcc-cartridge-overrides
